// Generated Data Model

export struct AppData {
    current-temp: float,
    target-temp: float,
    humidity: float,
    air-quality-index: float,
    hvac-status: string,
    wifi-status: string,
    filter-status: string,
    temp-unit: string,
    brightness: float,
    sleep-mode: bool,
    eco-mode: bool,
    fan-speed: string,
    schedule-enable: bool,
    filter-reminder-days: float,
    version: string,
}
